"""Review guidance is intentionally contextual; severities are triage defaults."""
from .models import Rule


def rule(id, title, severity, cwe, remediation, review):
    return Rule(id, title, severity, cwe, remediation, review)


RULES = {r.id: r for r in [
    rule("PY001", "Dynamic SQL statement", "high", 89,
         "Use driver placeholders and pass values separately. Allowlist any dynamic table or column identifiers.",
         "Confirm this is a database API and determine whether any part of the statement is externally controlled."),
    rule("PY002", "Shell command construction", "high", 78,
         "Use an argument list with shell=False, a fixed executable and validated arguments. Avoid invoking a shell.",
         "Trace each value into the command; fixed commands and trusted maintenance scripts may be acceptable."),
    rule("PY003", "Dynamic Python execution", "high", 95,
         "Replace eval/exec with explicit dispatch or a parser for a narrowly defined data format.",
         "Determine whether an untrusted party can influence the evaluated text."),
    rule("PY004", "Unsafe object deserialization", "high", 502,
         "Use a data-only format such as JSON with schema validation. Never load untrusted pickle or marshal data.",
         "Establish who can create or modify the serialized bytes, including stored files and cache entries."),
    rule("PY005", "Unsafe YAML loader", "high", 502,
         "Use yaml.safe_load or an explicitly selected SafeLoader/CSafeLoader.",
         "Check the installed PyYAML version and loader. Some modern versions reject a missing Loader instead of loading."),
    rule("PY006", "TLS certificate verification disabled", "high", 295,
         "Enable certificate and hostname verification; configure a trusted CA bundle when needed.",
         "Confirm the setting is reachable in production and review the connection's trust requirements."),
    rule("PY007", "Weak hash algorithm", "medium", 327,
         "Use a modern hash for integrity; use a dedicated password KDF such as Argon2id for passwords.",
         "MD5/SHA-1 can be acceptable for non-security checksums. Identify the actual security use."),
    rule("PY008", "Predictable randomness in a security value", "medium", 330,
         "Use the secrets module for tokens, reset links, passwords and other security values.",
         "Confirm the value is security-sensitive rather than a simulation, test or display identifier."),
    rule("PY009", "Race-prone temporary filename", "medium", 377,
         "Use tempfile.TemporaryFile, NamedTemporaryFile or mkstemp and retain the returned file handle.",
         "Check filesystem permissions and whether another process can create the path before it is opened."),
    rule("PY010", "Development debugger enabled", "high", 489,
         "Disable debug mode in production and run the application behind an appropriate production server.",
         "Determine which environment runs this entry point and whether it is network-accessible."),
    rule("PY011", "Dynamic template source", "high", 1336,
         "Keep template source fixed and pass untrusted content only as template data.",
         "Determine whether the value is template source or an ordinary template variable."),
    rule("PY012", "HTML escaping bypassed", "medium", 79,
         "Preserve template autoescaping. Sanitize intentionally supported rich HTML using a maintained allowlist sanitizer.",
         "Trace the value and verify output encoding for the exact HTML, attribute, URL or script context."),
    rule("PY013", "Input influences an outbound URL", "high", 918,
         "Allowlist destinations and schemes, validate resolved addresses and redirects, and enforce network egress restrictions.",
         "Confirm external control and check whether access to internal services or credentials is possible."),
    rule("PY014", "Input influences a filesystem path", "high", 22,
         "Resolve paths under a fixed allowed directory, enforce containment and consider symlink races; prefer opaque file IDs.",
         "Check the operation, allowed base directory, authorization and any validation before filesystem access."),
    rule("PY015", "Archive extraction requires containment review", "medium", 22,
         "Use a safe extraction filter supported by your Python version and enforce path, link, file-count and size limits.",
         "Identify the archive type and runtime version. Zip and tar APIs have different safeguards; inspect member handling."),
    rule("PY016", "JWT signature verification disabled", "high", 347,
         "Verify the signature using a trusted key and fixed permitted algorithms; validate issuer, audience and lifetime.",
         "Confirm decoded claims are not trusted for authentication or authorization without verification."),
    rule("PY017", "Input influences a redirect", "medium", 601,
         "Use fixed relative destinations or an explicit allowlist of approved redirect origins and paths.",
         "Verify scheme, host and path validation and the framework's redirect behavior."),
    rule("JS001", "Dynamic JavaScript execution", "high", 95,
         "Replace eval or Function construction with explicit dispatch or JSON parsing and schema validation.",
         "This lexical match does not prove the callable's identity or input trust; trace the evaluated value."),
    rule("JS002", "Potential shell execution", "high", 78,
         "Use execFile/spawn with shell disabled, a fixed executable and validated arguments.",
         "Confirm this is Node child_process execution, then trace command input; similarly named APIs may be unrelated."),
    rule("JS003", "Raw HTML insertion", "medium", 79,
         "Use textContent for text. Sanitize supported HTML with a maintained sanitizer and consider Trusted Types.",
         "Determine whether the inserted value is untrusted and whether a context-appropriate sanitizer is applied."),
    rule("JS004", "TLS certificate verification disabled", "high", 295,
         "Remove the verification bypass and configure trusted certificate authorities.",
         "Confirm this option configures a TLS client and is reachable in production."),
    rule("JS005", "Potential SQL string construction", "high", 89,
         "Use parameterized queries with values passed separately; allowlist dynamic identifiers.",
         "This heuristic examines a local call window. Confirm the database API, query construction and input trust."),
    rule("JS006", "React HTML escaping bypassed", "medium", 79,
         "Render text as ordinary React children; sanitize any intentionally supported raw HTML.",
         "Trace the __html value and verify sanitization before rendering."),
    rule("CFG001", "Debug configuration enabled", "medium", 489,
         "Disable debug output and detailed error pages in production configuration.",
         "Check environment overrides and whether this file is used by a deployed application."),
    rule("CFG002", "Secure cookie flag disabled", "medium", 614,
         "Enable Secure on authentication/session cookies and serve the application over HTTPS.",
         "Confirm the cookie's sensitivity and effective production settings."),
    rule("CFG003", "HttpOnly cookie flag disabled", "medium", 1004,
         "Enable HttpOnly on session cookies that client-side JavaScript does not need to access.",
         "Identify the cookie and whether its value should be accessible to JavaScript."),
    rule("CFG004", "Wildcard host allowlist", "medium", 20,
         "Set an explicit list of trusted hostnames and validate proxy forwarding configuration.",
         "Check whether upstream host validation provides the required protection."),
    rule("CFG005", "CORS allows all origins", "medium", 942,
         "Restrict origins to trusted applications and review credentialed cross-origin requests.",
         "Public unauthenticated resources may intentionally allow all origins; review the exposed data and credentials."),
    rule("CFG006", "Container explicitly runs as root", "medium", 250,
         "Run the final image as a dedicated non-root user with only required filesystem and kernel privileges.",
         "Check the final build stage and deployment security context, which may override the image user."),
    rule("SEC001", "Possible hardcoded credential", "high", 798,
         "Move credentials to a secret manager or runtime environment. Rotate any real exposed credential and review its use.",
         "The value is withheld. Confirm it is a live credential rather than an example, public identifier or test fixture."),
    rule("SEC002", "Private key material marker", "high", 321,
         "Remove private keys from source control, rotate exposed keys and store replacements in managed secret storage.",
         "Confirm the marker belongs to actual private key material; public keys and test fixtures require different handling."),
    rule("SEC003", "Credential token pattern", "high", 798,
         "Revoke and replace any real exposed token; load replacements from a secret manager and review repository history.",
         "A provider-shaped token is not proof it is valid. Do not attempt to validate it against a remote service."),
]}
